modules/netboot.nix
Fixes `nix-instantiate configuration.nix --show-trace` for me,
at least after running `./nix/update-ofborg-path.sh`.
Hope this helps!
There are other differences with upstream's netboot.nix,
but left this alone and just changed the part preventing eval.
=> netboot: fixup for Nix 2 and recent changes

configuration.nix, users.nix
```
[15:31:04] <gchristensen> I'd like to make some people able to sudo in order to reboot the box or whatever to handle minor problems like out of disk space or whatever. anyone want to have this access?
[...]
[15:47:50] <samueldr> gchristensen: and to actually answer, interested, let's hope I never have to use it (except maybe for a garbage collection through reboot)
[15:48:07] <samueldr> (I mean, things are going well generally!)
[15:48:21] <gchristensen> mind sending a PR adding a "canSudo" flag to the user list, and making sudo passwordless? :)
[15:48:29] -*- samueldr notes for later
```
Now that we're later, it is done.
I did **not** add a `canSudo` flag since there was already a `sudo` flag; if the desire was to actually add another group for sudo purposes, I will amend the PR as …
=> Adds passwordless sudo to wheel + sudo auth.

configuration.nix
This makes reuse of a single SSH connection for multiple builds more
useful (the default limit is 10), avoiding the need for
reauthenticating on each connection.
=> ssh: increase MaxSessions

README.md, configuration.nix
This allows getting a clone of nixpkgs significantly faster, using
$ git clone https://github.com/nixos/nixpkgs --reference /tmp/nixpkgs
which allows the majority of the objects to be fetched from the local
copy rather than github.
```
[lheckemann@aarch64:~]$ time git clone https://github.com/nixos/nixpkgs
Cloning into 'nixpkgs'...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 1556267 (delta 1), reused 1 (delta 1), pack-reused 1556255
Receiving objects: 100% (1556267/1556267), 946.78 MiB | 28.35 MiB/s, done.
Resolving deltas: 100% (1066108/1066108), done.
Checking out files: 100% (19085/19085), done.
real    2m6.898s
user    4m40.698s
sys     0m19.442s
[lheckemann@aarch64:~]$ time git …
```
=> Clone nixpkgs on boot

README.md
This can cause issues. To quote [1] @cleverca22 on irc:
```
<clever> id recomend against using `--option system`, that will break a lot of things
<clever> if you use `--option system`, then your lying to nix that the LOCAL machine is aarch64, which causes builtins.currentSystem to repeat that lie, and nix will try to run aarch64 binaries (causing your issue)
<clever> if you use `--argstr system aarch64-linux`, then your telling nixpkgs to do an aarch64 build, and leaving the local arch intact
```
What we want to do here is to tell nix to build for aarch64. We can do
that by passing the `system` argument to the top-level default.nix in
nixpkgs. `--option system` will override `builtins.currentSystem`
instead, which will override the default value of the `system` argument
as well but will …
=> Do not recommend overriding the currentSystem

configuration.nix
This solves an issue with remote building from stable nix which is the
stable distribution of nix.
If users need the unstable Nix on the machine for local testing of their
flakes, ca-derivations, ... they can just nix-shell -p nixUnstable for
their experiments.
See also: https://github.com/NixOS/nix/issues/4664
=> Stick to stable nix

keys/noneucat, users.nix
To build and test PinePhone-specific derivations for mobile NixOS
cc @samueldr @grahamc
=> add @noneucat as trusted user

keys/lukegb, users.nix
I sometimes need to test things on aarch64-linux and I _still_ haven't
gotten around to setting up my Oracle Cloud machine...
=> Add @lukegb as trusted user

keys/artturin, users.nix
=> add artturin as trusted user

keys/dguibert, users.nix
=> add dguibert as trusted user

armv7l.nix, configuration.nix
This patch along with [changes in nix](https://github.com/NixOS/nix/pull/5276) should allow to use aarch64 machines as armv7l builders.
See also https://github.com/NixOS/nixpkgs/pull/25240#issuecomment-1146564193
CC @lheckemann @grahamc
=> Apply kernel personality patch from Ubuntu and configure armv7l support.

build.sh, configuration.nix
Seems this repo needs a few changes to adapt to the changes in https://github.com/NixOS/equinix-metal-builders/pull/14 so for now I've just pinned it to the older commit and fixed the utillinux throw so it builds again.
cc @grahamc @Mic92
=> various fixes

configuration.nix, users.nix
Sudo is for troubleshooting or rebooting the box, see https://github.com/nix-community/aarch64-build-box/pull/35, https://github.com/nix-community/aarch64-build-box/pull/36
cc @nix-community/infra
=> Various changes

keys/lily, users.nix
I've been doing a lot more testing on aarch64 for my nixpkgs work, but the only aarch64 system I actually have is a Raspberry Pi. So it would be lovely to be able to use the community builder for testing some of that work
Thank you!
=> add lily to trusted users

keys/raitobezarius, users.nix
I am working on https://github.com/nix-community/lanzaboote/pull/31 and this machine seems to have nested virt, this would be useful for tests :).
=> add raitobezarius as trusted user

armv7l.nix, modules/netboot.nix
Since https://github.com/NixOS/nixpkgs/commit/91dd8b932457a45f08be3d4d355c12cbb1703774, `make-squashfs.nix` takes a `lib` argument as well.
=> netboot: fixup

configuration.nix
=> configuration: don't log refused connections

post-devices.sh
Reverts nix-community/aarch64-build-box#170
---
Probably causing the recent kernel panics that locks everything up. Gonna try and get this deployed so that ofborg can catch up in its aarch64 queue (and I don't have to keep rebooting the box every ~900 seconds, according to dmesg).
=> Revert "post-devices.sh: add the other NVMe device to the pool as well"

post-devices.sh
Reverts nix-community/aarch64-build-box#173
---
Still happens without this so let's bring it back for more disk space, if the machine ever lives for more than 10 minutes.
=> Revert "Revert "post-devices.sh: add the other NVMe device to the pool as well""

README.md
This way people can build NixOS tests right from the start, and the build box seems to be able to do so.
=> Make example config in the readme ready for building NixOS tests

keys/w4tsn, users.nix
=> users.nix: add w4tsn

keys/sebtm, users.nix
I'm nixpkgs/home-manager maintainer, recently trying to use/help out with https://github.com/tstat/raspberry-pi-nix and attempts to build/improve NixOS on the BPI-R3 why I would like to request access to the shared aarch64-builder.
=> Add SebTM to trusted users
